```yaml name=.github/workflows/blank.yml url=https://github.com/Lukspec/Lukspec/blob/b685416bd7d03b693d05c929aaf6767a8549ba09/.github/workflows/blank.yml
name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Lukspec
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          personal_token: ${{ secrets.PAGES_TOKEN }}
